CREATE TABLE Empresa( 
IdEmpresa INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
CedulaJuridica CHAR(12) NOT NULL UNIQUE,
Nombre VARCHAR(150) NOT NULL,
Telefono CHAR(9),
FechaCreacion DATETIME NOT NULL DEFAULT GETDATE(),
CantidadBeneficios tinyint NOT NULL,
FrecuenciaPago VARCHAR(9) NOT NULL,
DiaPago1 TINYINT NOT NULL,
DiaPago2 TINYINT,
Estado VARCHAR(8) NOT NULL DEFAULT 'Activo',
IdCreadoPor int NOT NULL,
CONSTRAINT CK_DiaPago1 CHECK (DiaPago1 BETWEEN 1 AND 31),
CONSTRAINT CK_DiaPago2 CHECK (DiaPago2 BETWEEN 1 AND 31),
CONSTRAINT CK_EstadoEmpresa CHECK (Estado IN ('Activo','Inactivo')),
CONSTRAINT FK_CreadoPor FOREIGN KEY (IdCreadoPor)
REFERENCES Usuario(IdUsuario)
ON DELETE NO ACTION
ON UPDATE CASCADE
) 
GO