CREATE TABLE UsuariosPorEmpresa( 
IdUsEmp INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
IdEmpresa INT NOT NULL,
IdUsuario INT NOT NULL,
CONSTRAINT FK_EmpresaPadre FOREIGN KEY (IdEmpresa)
REFERENCES Empresa(IdEmpresa)
ON DELETE NO ACTION
ON UPDATE NO ACTION, 
CONSTRAINT FK_UsuarioHijo FOREIGN KEY (IdUsuario)
REFERENCES Usuario(IdUsuario)
ON DELETE NO ACTION
ON UPDATE NO ACTION
) 
GO