CREATE TABLE Direccion( 
IdDireccion INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
IdDivision INT NOT NULL,
OtrasSenas VARCHAR(250) NULL,
IdEmpresa INT,
IdPersona INT,
CONSTRAINT FK_DivisionCR FOREIGN KEY (IdDivision)
REFERENCES DivisionTerritorialCR(IdDivision)
ON DELETE NO ACTION
ON UPDATE CASCADE,
CONSTRAINT FK_DireccionEmpresa FOREIGN KEY (IdEmpresa)
REFERENCES Empresa(IdEmpresa)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT FK_DireccionPersona FOREIGN KEY (IdPersona)
REFERENCES Persona(IdPersona)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT CK_DuenoDireccion CHECK ((IdEmpresa IS NOT NULL AND IdPersona IS NULL) OR (IdEmpresa IS NULL AND IdPersona IS NOT NULL))
)
GO